name: terlinet_gestos
description: "Tradutor de Libras com IA - TerlineT Pounds"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.1.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
